main/urls.py
from django.conf import settings
from django.urls import include, path

from .views import *

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    
] 




"""
URL configuration for uacademy project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

school/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from .views import *


urlpatterns = [
    path('grades/', GradesOfSchoolView.as_view(), name='grades_of_school'),
    path('grade/<slug:grade_slug>/', SubjectsOfGradeView.as_view(), name='subjects_of_grade'),
    # path('grade/<slug:grade_slug>/subject/<slug:subject_slug>/', ChaptersOfCourseView.as_view(), name='chapters_of_course'),
    path('grade/<slug:grade_slug>/subject/<slug:subject_slug>/content/', ChaptersTopicsView.as_view(), name='chapters_topics'),
    # path('grade/<slug:grade_slug>/subject/<slug:subject_slug>/<slug:chapter_slug>/', TopicsOfChapterView.as_view(), name='topics_of_chapter'),
    path('grade/<slug:grade_slug>/subject/<slug:subject_slug>/<slug:chapter_slug>/<slug:topic_slug>/', VideosOfTopicView.as_view(), name='videos_of_topic'),
    path('random/', RandomTopicView.as_view(), name='random_topic'),
    path('empty_topics/', show_topics, name='empty_topics'),
    path('subjects_all/', SubjectsAllView.as_view(), name='subjects_all'),
    
]


"""
URL configuration for uacademy project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

uacademy/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('school/', include('school.urls')),

]


"""
URL configuration for uacademy project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

school/models.py
from django.db import IntegrityError
from django.db import transaction
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.core.exceptions import ObjectDoesNotExist
from autoslug import AutoSlugField
from slugify import slugify
from django.core.exceptions import ValidationError
from django.core.validators import URLValidator
from django.core.validators import MinValueValidator, MaxValueValidator
import random
import re


# ---- Тип школи -------------------
class GradeType(models.Model):
    title = models.CharField(
        verbose_name='Тип школи',
        max_length=50, 
        unique=True, 
        )
    is_active = models.BooleanField(
        verbose_name='Виводити', 
        default=True
        )
    sort_order = models.IntegerField(
        verbose_name="Порядок виводу",
        help_text="Якщо поле залишиться пустим, то після збереженні елемент буде виводитися останнім.",
        null=True,
        blank=True,
        )
    objects = models.Manager()  # для можливості створення запитів до БД

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name = 'Тип школи'
        verbose_name_plural = 'Додатковий довідник: Типи школи'

    
# ---- Клас -------------------
class Grade(models.Model):
    title = models.CharField(
        verbose_name='Назва класу', 
        help_text='Додайте до назви слово клас, щоб користувачу було більш зрозуміло.',
        max_length=50, 
        unique=True, 
        )
    grade_type = models.ForeignKey(
        GradeType, 
        verbose_name="Тип школи",
        on_delete=models.PROTECT, 
        )
    is_active = models.BooleanField(
        verbose_name='Виводити',
        default=True,
        )
    sort_order = models.IntegerField(
        verbose_name="Порядок виводу", 
        help_text="Якщо поле залишиться пустим, то після збереженні елемент буде виводитися останнім.",
        null=True,
        blank=True,
        )
    slug = models.SlugField(
        verbose_name="slug",
        help_text="заповнюється автоматично",
        unique=True,
        blank=False,
        editable=False,
        max_length=50,
        )
    objects = models.Manager()  # для можливості створення запитів до БД

    def __str__(self):
        return self.title
    
    def save(self):
        self.slug = slugify(self.title)
        super(Grade, self).save()

    def get_absolute_url(self):
       # return reverse ('subjects', kwargs={'slug':self.slug})
       # return f"/courses/n/"
         return f"/courses/{self.slug}/"

    class Meta:
        verbose_name = 'Клас'
        verbose_name_plural = 'Довідник 1: Класи'


# ---- Наукова дисципліна -------------------
class Science(models.Model):
    title = models.CharField(
        verbose_name="Назва наукової дисципліни",
        max_length=100, 
        unique=True,
        )
    is_active = models.BooleanField(
        verbose_name="Виводити",
        default=True,
        )
    sort_order = models.IntegerField(
        verbose_name="Порядок виводу",
        help_text="Якщо поле залишиться пустим, то після збереженні елемент буде виводитися останнім.",
        null=True,
        blank=True,
        )
    slug = models.SlugField(
        verbose_name="slug",
        help_text="заповнюється автоматично",
        unique=True,
        blank=False,
        editable=False,
        max_length=100,
        )
    objects = models.Manager()  # для можливості створення запитів до БД

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Наукова дисципліна'
        verbose_name_plural = 'Додатковий довідник: Наукові дисципліни'


# ---- Предмет -------------------
class Subject(models.Model):
    title = models.CharField(
        verbose_name="Назва предмету",
        max_length=100, 
        unique=True,
        )
    is_active = models.BooleanField(
        verbose_name="Виводити",
        default=True,
        )
    sort_order = models.IntegerField(
        verbose_name="Порядок виводу",
        help_text="Якщо поле залишиться пустим, то після збереженні елемент буде виводитися останнім.",
        null=True,
        blank=True,
        )
    slug = models.SlugField(
        verbose_name="slug",
        help_text="заповнюється автоматично",
        unique=True,
        blank=False,
        editable=False,
        max_length=100,
        )
    objects = models.Manager()  # для можливості створення запитів до БД

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Предмет'
        verbose_name_plural = 'Довідник 2: Предмети'


# ---- Курс (Клас-Предмет) -------------------
class GradeSubject(models.Model):
    grade = models.ForeignKey(
        Grade,
        verbose_name="Клас",
        on_delete=models.PROTECT,
        )
    subject = models.ForeignKey(
        Subject,
        verbose_name="Предмет",
        on_delete=models.PROTECT,
        )
    title = models.CharField(
        verbose_name="Клас-Предмет (курс)",
        help_text="заповнюється автоматично",
        max_length=150,
        blank=True,
        unique=True,
        editable=False,
        )
    is_active = models.BooleanField(
        verbose_name="Активно", 
        default=True,
        )
    objects = models.Manager()  # для можливості створення запитів до БД

    def __str__(self):
        return self.grade.title+' - '+self.subject.title

    def save(self):
        if not self.title:
            self.title = f"{self.grade.title} - {self.subject.title}"
        super(GradeSubject, self).save()

    class Meta:
        verbose_name = 'Курс (Клас-Предмет)'
        verbose_name_plural = 'Довідник 3: Курси (Клас-Предмет)'
        unique_together = ('grade', 'subject')


# ---- Розділ -------------------
class Chapter(models.Model):
    course = models.ForeignKey(
        GradeSubject,
        verbose_name="Курс (Клас-Предмет)",
        on_delete=models.PROTECT,
        )
    sort_order = models.IntegerField(
        verbose_name="Номер розділу", 
        help_text="Номер розділу потрібен, щоб вивести розділи в правильному порядку",
        null=False,
        blank=False,
        )
    title = models.CharField(
        verbose_name="Назва розділу",
        max_length=255,
        unique=True,
        )
    description = models.TextField(
        verbose_name="Опис розділу",
        max_length=2000, 
        blank=True,
        )
    is_active = models.BooleanField(
        verbose_name="Виводити",
        default=True,
        )
    slug = models.SlugField(
        verbose_name="slug",
        help_text="заповнюється автоматично",
        unique=True,
        blank=False,
        editable=False,
        max_length=255,
        )
    objects = models.Manager()  # для можливості створення запитів до БД

    def save(self, *args, **kwargs):
        # Генеруємо Slug на основі поля title
        self.slug = slugify(self.title)
        super(Chapter, self).save(*args, **kwargs)

    def __str__(self):
        return self.course.title + ' - ' + self.title

    class Meta:
        verbose_name = 'Розділ'
        verbose_name_plural = '1. Розділи'



# ---- Тема -------------------
class Topic(models.Model):
    chapter= models.ForeignKey(
        Chapter,
        verbose_name="Розділ",
        on_delete=models.PROTECT,
        )
    sort_order = models.IntegerField(
        verbose_name="Номер теми", 
        help_text="Номер теми потрібен, щоб вивести теми в правильному порядку",
        null=False,
        blank=False,
        )
    title = models.CharField(
        verbose_name="Назва теми",
        max_length=255,
        unique=True,
        )
    description = models.TextField(
        verbose_name="Опис теми",
        max_length=2000, 
        blank=True,
        )
    science = models.ForeignKey(
        Science,
        verbose_name="Наукова дисципліна",
        on_delete=models.PROTECT,
        )
    is_active = models.BooleanField(
        verbose_name="Виводити",
        default=True,
        )
    sort_order_full_dec = models.DecimalField(
        verbose_name = "Порядок виводу",
        help_text="Розраховується автоматично",
        max_digits=8, # Максимальна кількість цифр, включаючи десяткові
        decimal_places = 4, # Кількість цифр після десяткової коми
        null=True,
        blank=True,
        editable=False,
    )
    slug = models.SlugField(
        verbose_name="slug",
        help_text="заповнюється автоматично",
        unique=True,
        blank=False,
        editable=False,
        max_length=255,
        )
    objects = models.Manager()  # для можливості створення запитів до БД

    def __str__(self):
        return self.chapter.course.title + '-' + self.chapter.title + '-' + self.title
    
    def save(self):
        self.sort_order_full_dec = self.chapter.sort_order * 1 + self.sort_order * 0.0001
        super(Topic, self).save()

    class Meta:
        verbose_name = 'Тема'
        verbose_name_plural = '2. Теми'


# ---- Автори підручників -------------------
class TextBookAuthor(models.Model):
    title = models.CharField(
        verbose_name="Автор(и) підручника",
        help_text="Вкажіть ПІБ у вигляді ''Т.Тарасенко''",
        max_length=255,
        unique=True,
        )
    is_active = models.BooleanField(
        verbose_name="Виводити",
        default=True,
        )
    slug = models.SlugField(
        verbose_name="slug",
        help_text="заповнюється автоматично",
        unique=True,
        blank=False,
        editable=False,
        max_length=255,
        )
    objects = models.Manager()  # для можливості створення запитів до БД

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Автор підручника'
        verbose_name_plural = 'Довідник для підручників: Автори підручників'


# ---- Підручники -------------------
class TextBook(models.Model):
    course = models.ForeignKey(
        GradeSubject,

school/forms.py
from django import forms
from .models import *

# class GradeSelectionForm(forms.Form):
#     grade = forms.ModelChoiceField(queryset=Grade.objects.filter(is_active=True))

school/templates/school/_layout.html
{% extends 'main/_layout.html' %}

<!-- Тут будуть підключені стилі зі статичного файлу для кожного додатку -->
{% block custom_styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'school/css/styles.css' %}">
    <script src="{% static 'school/js/scripts.js' %}"></script>
{% endblock %}

school/templates/school/chapters_of_course.html
{% extends 'school/_layout.html' %}

{% block title %}
    Предмети
{% endblock %}


{% block content %}
    <!-- Breadcrumbs -->
  <ul class="breadcrumb">
    <li><a href="{% url 'grades_of_school' %}">Класи</a></li>
    <li><a href="{% url 'subjects_of_grade' grade_slug=grade.slug %}"> Предмети</a></li>
    <li>Розділи</li>
  </ul>

  <h5><a href="{% url 'subjects_of_grade' grade_slug=grade.slug %}">{{ grade.title }}</a>
    - {{ subject.title }}
  </h5>

  <div id="div-top">
  Виберіть розділ:
  {% for chapter in chapters %}
  <div id="div-top">
    <ul>
      <li>
          <a href="{% url 'topics_of_chapter' grade_slug=grade.slug subject_slug=subject.slug chapter_slug=chapter.slug %}"> {{ chapter.title }} </a>
      </li>
    </ul>
  </div>
  {% endfor %}
  </div>

{% endblock %}

school/templates/school/chapters_topics.html
{% extends 'school/_layout.html' %}

{% block title %}
    Предмети
{% endblock %}


{% block content %}
    <!-- Breadcrumbs -->
  <ul class="breadcrumb">
    <li><a href="{% url 'grades_of_school' %}">Класи</a></li>
    <li><a href="{% url 'subjects_of_grade' grade_slug=grade.slug %}"> Предмети</a></li>
    <li>Розділи</li>
  </ul>

  <h5><a href="{% url 'subjects_of_grade' grade_slug=grade.slug %}">{{ grade.title }}</a>
    - {{ subject.title }}
  </h5>

  <div id="div-top">
  Виберіть тему:

  {% for chapter in chapters %}
  <div id="div-top">
    <h4>{{ chapter.sort_order }}. {{ chapter.title }}</h4>
    <ul>
        {% for topic in chapter.topic_set.all %}
            <li>
              <a href="{% url 'videos_of_topic' grade_slug=grade.slug subject_slug=subject.slug chapter_slug=chapter.slug topic_slug=topic.slug %}">
                {% if topic == topic_current %}
                  <strong>{{ chapter.sort_order }}.{{ topic.sort_order }} {{ topic.title }}</strong>
                {% else %}
                {{ chapter.sort_order }}.{{ topic.sort_order }} {{ topic.title }}
                {% endif %}
              </a>
              <span id="div-small"> кількість відео: {{ topic.video_exist }}
              </span>
            </li>
        {% endfor %}
    </ul>
  </div>
  {% endfor %}
</div>

{% endblock %}

school/templates/school/empty_topics.html
{% extends 'school/_layout.html' %}

{% block title %}
    Теми уроків
{% endblock %}


{% block content %}
    <h3>Теми уроків</h3>
        {% if 0 %}
          <p>Тема1</p>
          <p>Тема2</p>
        {% else %}
            <p><i>Для цього класу та предмету поки не додано тем.</i></p>
            <p><i>Ви можете допомогти нам заповнити цю сторінку. <br>
            Зареєструйтесь і допомагайте створювати відеотеку для цікавого та легкого навчання</i></p>
        {% endif %}

{% endblock %}

school/templates/school/grades_of_school.html
{% extends 'school/_layout.html' %}

{% block title %}
    Класи
{% endblock %}


{% block content %}
    <br>
    <h4>Виберіть клас</h4>

    {% for grade in grades %}
    <div class="container" style="height: 3.5em;">
        <div class="d-grid gap-2">
             <a href="{% url 'subjects_of_grade' grade.slug %}" class="btn btn-lg btn-warning" id="SelectButton"> {{ grade.title }} </a>
         </div>
    </div>
    {% endfor %}

{% endblock %}

school/templates/school/subjects_all.html
{% extends 'school/_layout.html' %}

{% block title %}
    Предмети
{% endblock %}



{% block content %}
<div>
    <br>
    <h3>Всі предмети</h3>

    Активні:
    <ul>
        {% for el in subjects %}
            {% if el.is_active %}
                <li> {{ el.title }} </li>
          {% endif %}
        {% endfor %}
    </ul>

    Неактивні:
    <ul>
        {% for el in subjects %}
            {% if not el.is_active %}
              <li> {{ el.title }} </li>
           {% endif %}
        {% endfor %}
    </ul>
</div>
{% endblock %}

school/templates/school/subjects_of_grade.html
{% extends 'school/_layout.html' %}

{% block title %}
    Предмети
{% endblock %}


{% block content %}
    <!-- Breadcrumbs -->
  <ul class="breadcrumb">
    <li><a href="{% url 'grades_of_school' %}">Класи</a></li>
    <li>Предмети</li>
  </ul>

  <h5> {{ grade.title }}</h5>
  <p>Виберіть предмет:</p>
  {% for item in topic_chapter_list %}
    <div class="container">
          {% if item.1 and item.2 %}
            <div style="height: 3.5em;">
              <a href="{% url 'videos_of_topic' grade_slug=grade.slug subject_slug=item.0.slug chapter_slug=item.1.slug topic_slug=item.2.slug %}" class="btn btn-lg btn-warning col-6" id="SelectButton"> {{ item.0.title }} </a>
              <a href="{% url 'chapters_topics' grade_slug=grade.slug subject_slug=item.0.slug %}"> <i style="padding-left: 10px;"> До списку тем </i></a>
            </div>
            {% endif %}
    </div>
  {% endfor %}

{% endblock %}

school/templates/school/topic_nav.html
<div>
    <!-- Кнопки для переходу по контенту -->

    <div class="col-12 d-flex justify-content-between">

      <div class="col-6 d-flex" id="div-btn">
        {% if topic_pre and nav_pre%}
          <a href="{% url 'videos_of_topic' grade_slug=grade.slug subject_slug=subject.slug chapter_slug=chapter_pre.slug topic_slug=topic_pre.slug %}" class="btn btn-warning col-12">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
            </svg>
             Попередня: <strong>{{ topic_pre.title }}</strong></a>
        {% endif %}
      </div>

      <div class="col-6 d-flex" id="div-btn">
        {% if topic_next and nav_next%}
          <a href="{% url 'videos_of_topic' grade_slug=grade.slug subject_slug=subject.slug chapter_slug=chapter_next.slug topic_slug=topic_next.slug %}" class="btn btn-warning col-12">
          Наступна: <strong>{{ topic_next.title }}</strong> 
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/>
          </svg>
        </a>
            
              <!-- <button type="button" class="btn btn-outline-info" id="SelectButton">btn-outline-info</button>
              <button type="button" class="btn btn-outline-warning" style="color: black;">btn-outline-warning</button>
              <button type="button" class="btn btn-primary">btn-primary</button>
              <button type="button" class="btn btn-outline-secondary">btn-outline-secondar</button>
              <button type="button" class="btn btn-outline-primary">btn-outline-primary</button>
              <button type="button" class="btn btn-outline-secondary">btn-outline-secondary</button> -->
        {% endif %}
      </div>

    </div>

  </div>

school/templates/school/topic_nav_main.html
<div>
  <!-- Кнопки для переходу по контенту -->
  <div class="col-12" id="div-btn">
    <a href="{% url 'chapters_topics' grade_slug=grade.slug subject_slug=subject.slug %}" class="btn btn btn-warning col-12">
     <strong>Всі теми</strong>
    </a>
  </div>

  <!-- <div class="col-12" id="div-btn">
    <a href="{% url 'chapters_topics' grade_slug=grade.slug subject_slug=subject.slug %}" class="btn btn-outline-primary col-12">
      Всі теми "<strong>{{ chapter.title }}</strong>"
    </a>
  </div> -->

</div>

school/templates/school/topics_of_chapter.html
{% extends 'school/_layout.html' %}

{% block title %}
    Предмети
{% endblock %}


{% block content %}
    <!-- Breadcrumbs -->
  <ul class="breadcrumb">
    <li><a href="{% url 'grades_of_school' %}">Класи</a></li>
    <li><a href="{% url 'subjects_of_grade' grade_slug=grade.slug %}">Предмети</a></li>
    <li><a href="{% url 'chapters_of_course' grade_slug=grade.slug subject_slug=subject.slug %}">Розділи</a></li>
    <li>Теми розділу</li>
  </ul>

  <h5><a href="{% url 'subjects_of_grade' grade_slug=grade.slug %}">{{ grade.title }}</a>
    - 
    <a href="{% url 'chapters_of_course' grade_slug=grade.slug subject_slug=subject.slug %}">{{ subject.title }}</a>
  </h5>
  <h4> Розділ: {{ chapter.title }}</h4>
  <p>Виберіть тему:</p>
  {% for topic in topics %}
  <ul>
    <li>
      <a href="{% url 'videos_of_topic' grade_slug=grade.slug subject_slug=subject.slug chapter_slug=chapter.slug topic_slug=topic.slug %}">
        {% if topic == topic_current %}
          <strong>{{ topic.title }}</strong>
        {% else %}
          {{ topic.title }}
        {% endif %}
      </a>
    </li>
  </ul>
  {% endfor %}

  Поточний розділ: {{ chapter_current.id }}
  <!-- <p>Поточна тема: {{ topic_current.title }} </p>
  <p>number_of_days_per_year: {{ number_of_days_per_year }} </p>
  <p>number_of_days_for_today: {{ number_of_days_for_today }} </p>
  <p>topics_num: {{ topics_num }} </p>
  <p>days_per_topic: {{ days_per_topic }} </p>
  <p>number_of_topic: {{ number_of_topic }} </p> -->

{% endblock %}

school/templates/school/videos_of_topic.html
{% extends 'school/_layout.html' %}

{% block title %}
    Предмети
{% endblock %}


{% block content %}
<div class="container">
 
  <div>
    <!-- Breadcrumbs -->
    <ul class="breadcrumb">
      <li><a href="{% url 'grades_of_school' %}">Класи</a></li>
      <li><a href="{% url 'subjects_of_grade' grade_slug=grade.slug %}">Предмети</a></li>
      <li><a href="{% url 'chapters_topics' grade_slug=grade.slug subject_slug=subject.slug %}">Розділи і теми</a></li>
      <li>Відео до теми</li>
    </ul>
  </div>

  <div>
    <!-- Заголовок сторінки -->
    <h5><a href="{% url 'subjects_of_grade' grade_slug=grade.slug %}">
       {{ grade.title }}</a>
        - 
       <a href="{% url 'chapters_topics' grade_slug=grade.slug subject_slug=subject.slug %}">
        {{ subject.title }}</a>
    </h5>
  </div>


  <div>
    <!-- Кнопки для переходу по контенту -->
    {% include 'school/topic_nav_main.html' %}
    {% include 'school/topic_nav.html' %} 
  </div>

  <div>
    <!-- Контент -->
    <div id="div-top">
      <h3> <strong style="font-weight: 400;">  Розділ: {{ chapter.title }} </strong> </h3>
      <h4> <strong style="font-weight: 700;"> Тема: {{ topic.title }}</strong> </h4>
      <p style="font-weight: 400;"> {{ topic.description|linebreaksbr|safe }}</p>
    </div>
    <div>
      {% if videos %}
        {% for video in videos %}
        <hr>
           <!-- Блок з назвою відео та самим відео -->
          <div id="div-bottom">
              <!-- Блок опису відео -->
              <strong style="font-weight: 500;"> Назва відео: {{ video.title }}</strong>
              <div> {{ video.topic_video_desc|linebreaksbr|safe }}
              </div>

            <!-- Блок самого відео -->
            <div style="font-weight: 400;" id="div-top">
              <div class="col-12 d-flex justify-content-between">
                <div class="col-6 d-flex" id="div-info">Рівень: {{ video.level }} 
                </div>
                <div class="col-6 d-flex justify-content-end" id="div-info">
                  <!-- <div>Рейтинг: {{ video.rating }} (з 12)
                  </div> -->
                </div>
              </div>

              <div class="video-container">
                <iframe class="responsive-iframe" src="{{ video.link }}" frameborder="10" data-aspect-ratio="16/9" allowfullscreen></iframe>
              </div>
                <div> {{ video.description|linebreaksbr|safe}}
                </div>
            </div>
          </div>
          {% endfor %}

          <div>
            <!-- Кнопки для переходу по контенту -->
            {% include 'school/topic_nav.html' %} 
          </div>

        {% else %}
          <p><i>Для цієї теми поки не додано жодного відео.</i></p>
        {% endif %}

      </div>
  </div>

</div>

{% endblock %}